### ISSUE TITLE
Errors on app startup

### ISSUE THREAD

**Issue by ito** [aaronksaunders/parse-starter-ionic#2] opened 2015-04-25 17:45 UTC
Hello Aaron,

When starting ionic serve I find these errors in my log.
I'm a Parse and Ionic beginner .. any ideas why this is happening?

ionic $ 0     400548   log      parse initialized in init function
1     400551   log      [object Object]
2     400557   log      [object Object]
3     400561   log      [object Object]
4     400564   log      [object Object]
5     400568   log      [object Object]
6     400569   error    Error: [$rootScope:infdig] 10 $digest() iterations reached. Aborting!
Watchers fired in the last 5 iterations: []

**Comment by aaronksaunders** [comment] 2015-05-25 02:11
@ito are you still seeing this issue, I have sometime over the holiday and was going to try and reproduce

**Comment by grantgumina** [comment] 2015-06-15 02:13
I'm seeing this issue as well. It's preventing me from deploying my application that's based on this starter projects to an Android emulator. Any updates?

**Comment by aaronksaunders** [comment] 2015-06-15 11:50
Never heard back js was about to close this issue, will investigate since you are seeing it now.

**Comment by grantgumina** [comment] 2015-06-15 23:06
Yeah I saw that. Thank you so much, please let me know if there's anything I can do to help you out.

**Comment by aaronksaunders** [comment] 2015-06-16 02:09
@grantgumina - i just ran this code with the latest ionic release and I am not seeing this error. I think i am going to need to see what changes, if any you have made to the code

**Comment by grantgumina** [comment] 2015-06-16 10:56
So I figured out the issue I was having. It had to do with the authentication code being run that checked if the user was logged in. Specifically this part:
    .state('tab', {
                url: "/tab",
                abstract: true,
                templateUrl: "templates/tabs.html",
                resolve: {
                    user: function(UserService) {
                        return UserService.init();
                    }
                }
            })

I stopped using that and instead put the following in the .run function:

```
var currentUser = Parse.User.current();
    $rootScope.user = null;
    $rootScope.isLoggedIn = false;

     if (currentUser) {
        $rootScope.user = currentUser;
        $rootScope.isLoggedIn = true;
        $state.go('tab.prospects');
    }
```

Thanks for responding to this. I'm guessing I was poking around in the UserServices functions and got myself into trouble.

**Comment by aaronksaunders** [comment] 2015-06-16 12:11
you really shouldn't be using the $rootScope like that.. but of it works for you have at it

**Comment by marclamberti** [comment] 2015-07-04 20:49
Actually the problem is still there and it is because in the otherwise statement you put $urlRouterProvider.otherwise('/tab/list');
But if there is no user, this creates a loop because of,
                resolve: {
                    user: function (UserService) {
                        var value = UserService.init();
                        return value;
                    }
                }
in the function init in UserService you do,
                    var currentUser = Parse.User.current();
                    if (currentUser) {
                        return $q.when(currentUser);
                    } else {
                        return $q.reject({error: "noUser"});
                    }
and since you use,
  $rootScope.$on('$stateChangeError',
            function (event, toState, toParams, fromState, fromParams, error) {

```
            console.log('$stateChangeError ' + error && (error.debug || error.message || error));

            // if the error is "noUser" the go to login state
            if (error && error.error === "noUser") {
                $state.go('app-login', {});
            }
        });
```

**Comment by marclamberti** [comment] 2015-07-05 17:45
To fix the infinite loop:
                if (error && error.error === "noUser") {
                  event.preventDefault()
                  $state.go('app-login', {});
                }

**Comment by aaronksaunders** [comment] 2015-07-05 17:51
I will check this, I use this exact code in client app now and I am not
seeing this error... So if I check out code as is and run it, I will see
the error?

On Sunday, July 5, 2015, marclamberti notifications@github.com wrote:

> To fix the infinite loop:
> if (error && error.error === "noUser") {
> event.preventDefault()
> $state.go('app-login', {});
> }
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/aaronksaunders/parse-starter-ionic/issues/2#issuecomment-118640446
> .

## 

## -- http://www.clearlyinnovative.com/build-it/

Aaron K. Saunders
CEO Clearly Innovative Inc.
aaron@clearlyinnovative.com
201.214.5926  (M)
blog@clearlyinnovative.com
www.clearlyinnovative.com
@aaronksaunders

This email message and any attachment(s) are for the sole use of the
intended recipient(s) and may contain proprietary and/or confidential
information which may be privileged or otherwise protected from disclosure.
Any unauthorized review, use, disclosure or distribution is prohibited. If
you are not the intended recipient(s), please contact the sender by reply
email and destroy the original message and any copies of the message as
well as any attachment(s) to the original message.

**Comment by marclamberti** [comment] 2015-07-05 18:00
Normally yes.

**Comment by bschippers718** [comment] 2015-07-12 16:46
Can't seem to create new user, just loads index page.  When I click on create new user link, nothing happens, any ideas?  Thanks!

**Comment by aaronksaunders** [comment] 2015-07-12 17:32
just committed a fix to the create account issue @bschippers718, in future please open new issue

**Closed as completed by aaronksaunders** 2015-07-12 17:32 UTC

**Comment by bschippers718** [comment] 2015-07-12 19:08
@aaronksaunders will do, my apologies.  Thank you!
